version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
  build-and-deploy:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: npx semantic-release
          name: Run Semantic Release
workflows:
  test-publish-to-npm-registry:
    jobs:
      - build-and-test
      - build-and-deploy:
          requires:
            - build-and-test
